export interface SheetSchema {
  title: string;
  headers: string[];
}

export const SHEETS: Record<string, SheetSchema> = {
  Contacts: {
    title: "Contacts",
    headers: [
      "id",
      "name",
      "email",
      "company",
      "role",
      "phone",
      "linkedin",
      "tags",
      "notes",
      "createdAt",
      "updatedAt",
    ],
  },
  Leads: {
    title: "Leads",
    headers: [
      "id",
      "contactId",
      "source",
      "stage",
      "score",
      "scoreReason",
      "value",
      "owner",
      "lastContactedAt",
      "nextActionAt",
      "nextAction",
      "notes",
      "createdAt",
      "updatedAt",
    ],
  },
  Campaigns: {
    title: "Campaigns",
    headers: [
      "id",
      "name",
      "goal",
      "audience",
      "status",
      "templateId",
      "sentCount",
      "repliedCount",
      "createdAt",
    ],
  },
  Emails: {
    title: "Emails",
    headers: [
      "id",
      "contactId",
      "campaignId",
      "sequenceEnrollmentId",
      "stepIndex",
      "variant",
      "subject",
      "body",
      "sentAt",
      "status",
      "aiGenerated",
      "prompt",
      "threadId",
      "repliedAt",
    ],
  },
  Templates: {
    title: "Templates",
    headers: ["id", "name", "subject", "body", "aiPrompt", "createdAt"],
  },
  Companies: {
    title: "Companies",
    headers: [
      "id",
      "name",
      "domain",
      "industry",
      "size",
      "website",
      "notes",
      "createdAt",
      "updatedAt",
    ],
  },
  Tasks: {
    title: "Tasks",
    headers: [
      "id",
      "contactId",
      "title",
      "dueAt",
      "status",
      "owner",
      "notes",
      "createdAt",
      "completedAt",
    ],
  },
  Activity: {
    title: "Activity",
    headers: [
      "id",
      "contactId",
      "type",
      "summary",
      "meta",
      "createdAt",
      "actor",
    ],
  },
  Sequences: {
    title: "Sequences",
    headers: [
      "id",
      "name",
      "goal",
      "tone",
      "status",
      "createdAt",
    ],
  },
  SequenceSteps: {
    title: "SequenceSteps",
    headers: [
      "id",
      "sequenceId",
      "stepIndex",
      "delayDays",
      "subjectHint",
      "instructions",
      "createdAt",
    ],
  },
  Enrollments: {
    title: "Enrollments",
    headers: [
      "id",
      "sequenceId",
      "contactId",
      "status",
      "currentStep",
      "nextRunAt",
      "lastRunAt",
      "createdAt",
      "stoppedReason",
    ],
  },
  Forms: {
    title: "Forms",
    headers: [
      "id",
      "slug",
      "name",
      "fields",
      "redirectUrl",
      "tags",
      "sequenceId",
      "createdAt",
    ],
  },
  Views: {
    title: "Views",
    headers: ["id", "name", "filter", "createdAt"],
  },
  Config: {
    title: "Config",
    headers: ["key", "value"],
  },
};

export const SHEET_NAMES = Object.keys(SHEETS) as Array<keyof typeof SHEETS>;
