// Sample data shipped with the static demo so first-time visitors land on a
// pre-populated CRM instead of an empty shell.

import type {
  Activity,
  Campaign,
  Company,
  Contact,
  EmailRecord,
  Enrollment,
  FormDef,
  Lead,
  SavedView,
  Sequence,
  SequenceStep,
  Task,
  Template,
} from "../types";

const NOW = "2026-04-30T10:00:00.000Z";
const D = (offsetDays: number) =>
  new Date(Date.parse(NOW) + offsetDays * 24 * 3600 * 1000).toISOString();

export const SEED_CONTACTS: Contact[] = [
  {
    id: "c_demo_001",
    name: "Maya Chen",
    email: "maya.chen@northwind.example",
    company: "Northwind Logistics",
    role: "VP Sales",
    phone: "+1 415 555 0142",
    linkedin: "https://linkedin.com/in/mayachen",
    tags: "ICP, mid-market",
    notes: "Met at SaaStr; expanding into EU next quarter.",
    createdAt: D(-21),
    updatedAt: D(-2),
  },
  {
    id: "c_demo_002",
    name: "Diego Alvarez",
    email: "diego@brightleaf.example",
    company: "Brightleaf Analytics",
    role: "Head of Growth",
    phone: "",
    linkedin: "https://linkedin.com/in/diegoalvarez",
    tags: "ICP, replied",
    notes: "Cares about pipeline analytics. Wants to see funnel reports.",
    createdAt: D(-14),
    updatedAt: D(-1),
  },
  {
    id: "c_demo_003",
    name: "Priya Nair",
    email: "priya@tidewater.example",
    company: "Tidewater AI",
    role: "Founder",
    phone: "",
    linkedin: "",
    tags: "ICP, founder",
    notes: "Series A, 25 people. Looking for outbound tooling.",
    createdAt: D(-9),
    updatedAt: D(-1),
  },
  {
    id: "c_demo_004",
    name: "Tom Becker",
    email: "tbecker@apexpartners.example",
    company: "Apex Partners",
    role: "Partner",
    phone: "",
    linkedin: "",
    tags: "investor",
    notes: "Intro from board; warm.",
    createdAt: D(-7),
    updatedAt: D(-3),
  },
  {
    id: "c_demo_005",
    name: "Sara Okafor",
    email: "sara.okafor@helixmed.example",
    company: "Helix Medical",
    role: "Director of Sales Ops",
    phone: "",
    linkedin: "",
    tags: "ICP, healthcare",
    notes: "Procurement gate is RevOps. Loop in IT.",
    createdAt: D(-5),
    updatedAt: D(-1),
  },
  {
    id: "c_demo_006",
    name: "Liam O'Connor",
    email: "liam@drift-bay.example",
    company: "Drift Bay",
    role: "Sales Manager",
    phone: "",
    linkedin: "",
    tags: "ICP",
    notes: "From CSV import.",
    createdAt: D(-3),
    updatedAt: D(-3),
  },
  {
    id: "c_demo_007",
    name: "Aiko Tanaka",
    email: "aiko@northwind.example",
    company: "Northwind Logistics",
    role: "Sales Engineer",
    phone: "",
    linkedin: "",
    tags: "champion",
    notes: "Maya's deputy. Pre-sold; needs ammunition.",
    createdAt: D(-2),
    updatedAt: D(-2),
  },
  {
    id: "c_demo_008",
    name: "Noah Rivera",
    email: "noah@cobalt-lab.example",
    company: "Cobalt Lab",
    role: "COO",
    phone: "",
    linkedin: "",
    tags: "ICP",
    notes: "Form submission from /f/contact-us.",
    createdAt: D(-1),
    updatedAt: D(-1),
  },
];

export const SEED_LEADS: Lead[] = [
  {
    id: "l_demo_001",
    contactId: "c_demo_001",
    source: "manual",
    stage: "engaged",
    score: 88,
    scoreReason:
      "Decision-maker title at ICP-fit company; replied to opener.",
    value: 36000,
    owner: "you@yourco.example",
    lastContactedAt: D(-2),
    nextActionAt: D(2),
    nextAction: "Send pricing one-pager",
    notes: "",
    createdAt: D(-21),
    updatedAt: D(-2),
  },
  {
    id: "l_demo_002",
    contactId: "c_demo_002",
    source: "linkedin",
    stage: "qualified",
    score: 92,
    scoreReason:
      "Replied within 30 minutes; explicit budget signal in note.",
    value: 24000,
    owner: "you@yourco.example",
    lastContactedAt: D(-1),
    nextActionAt: D(1),
    nextAction: "Demo Tuesday",
    notes: "",
    createdAt: D(-14),
    updatedAt: D(-1),
  },
  {
    id: "l_demo_003",
    contactId: "c_demo_003",
    source: "csv-import",
    stage: "contacted",
    score: 71,
    scoreReason: "Founder at Series A AI startup; outbound-tool ICP.",
    value: 12000,
    owner: "you@yourco.example",
    lastContactedAt: D(-1),
    nextActionAt: D(2),
    nextAction: "Follow-up step 2",
    notes: "",
    createdAt: D(-9),
    updatedAt: D(-1),
  },
  {
    id: "l_demo_004",
    contactId: "c_demo_004",
    source: "referral",
    stage: "won",
    score: 95,
    scoreReason: "Warm referral; closed pilot.",
    value: 18000,
    owner: "you@yourco.example",
    lastContactedAt: D(-3),
    nextActionAt: "",
    nextAction: "",
    notes: "",
    createdAt: D(-7),
    updatedAt: D(-3),
  },
  {
    id: "l_demo_005",
    contactId: "c_demo_005",
    source: "manual",
    stage: "new",
    score: 64,
    scoreReason: "ICP fit, no prior touch.",
    value: 30000,
    owner: "you@yourco.example",
    lastContactedAt: "",
    nextActionAt: D(0),
    nextAction: "First touch",
    notes: "",
    createdAt: D(-5),
    updatedAt: D(-1),
  },
  {
    id: "l_demo_006",
    contactId: "c_demo_006",
    source: "csv-import",
    stage: "new",
    score: 50,
    scoreReason: "Limited profile data.",
    value: 0,
    owner: "you@yourco.example",
    lastContactedAt: "",
    nextActionAt: D(0),
    nextAction: "Score with AI",
    notes: "",
    createdAt: D(-3),
    updatedAt: D(-3),
  },
  {
    id: "l_demo_007",
    contactId: "c_demo_007",
    source: "manual",
    stage: "engaged",
    score: 78,
    scoreReason: "Champion at known account; pre-sold internally.",
    value: 0,
    owner: "you@yourco.example",
    lastContactedAt: D(-2),
    nextActionAt: D(3),
    nextAction: "Send technical brief",
    notes: "",
    createdAt: D(-2),
    updatedAt: D(-2),
  },
  {
    id: "l_demo_008",
    contactId: "c_demo_008",
    source: "form:contact-us",
    stage: "contacted",
    score: 80,
    scoreReason: "Inbound form submission with company + role.",
    value: 15000,
    owner: "you@yourco.example",
    lastContactedAt: D(-1),
    nextActionAt: D(2),
    nextAction: "Sequence step 2",
    notes: "",
    createdAt: D(-1),
    updatedAt: D(-1),
  },
];

export const SEED_CAMPAIGNS: Campaign[] = [
  {
    id: "cmp_demo_001",
    name: "Q2 mid-market push",
    goal: "Book 20 demos with VP Sales / RevOps at mid-market companies.",
    audience: "VP Sales / Head of Sales Ops, 200-2000 employees",
    status: "active",
    templateId: "tpl_demo_001",
    sentCount: 32,
    repliedCount: 7,
    createdAt: D(-21),
  },
  {
    id: "cmp_demo_002",
    name: "Founder outreach",
    goal: "Land 5 design-partner conversations with Series A founders.",
    audience: "Founders / CEOs, 10-50 employees",
    status: "active",
    templateId: "",
    sentCount: 14,
    repliedCount: 3,
    createdAt: D(-14),
  },
];

export const SEED_TEMPLATES: Template[] = [
  {
    id: "tpl_demo_001",
    name: "Mid-market opener",
    subject: "Quick idea for {{company}}",
    body:
      "Hi {{firstName}},\n\nNoticed {{company}} is scaling outbound. " +
      "We help VPs of Sales like you ship 30% more pipeline with AI-personalized sequences.\n\n" +
      "Open to a 15-minute look next week?\n\n— {{senderName}}",
    aiPrompt:
      "Book an intro demo with a VP of Sales at a mid-market company. Reference scaling outbound.",
    createdAt: D(-21),
  },
  {
    id: "tpl_demo_002",
    name: "Founder breakup",
    subject: "Last note for now",
    body:
      "Hi {{firstName}},\n\nI'll stop pinging — but if outbound becomes a priority " +
      "in the next quarter, the offer stands.\n\n— {{senderName}}",
    aiPrompt:
      "Soft breakup email to a founder who has not replied to two prior emails.",
    createdAt: D(-14),
  },
];

export const SEED_EMAILS: EmailRecord[] = [
  {
    id: "e_demo_001",
    contactId: "c_demo_001",
    campaignId: "cmp_demo_001",
    sequenceEnrollmentId: "",
    stepIndex: "",
    variant: "A",
    subject: "Quick idea for Northwind Logistics",
    body:
      "Hi Maya,\n\nNoticed Northwind is scaling outbound into EU. We help VPs of Sales " +
      "like you ship 30% more pipeline with AI-personalized sequences.\n\n" +
      "Open to a 15-min look next week?\n\n— You",
    sentAt: D(-7),
    status: "sent",
    aiGenerated: "yes",
    prompt: "Book an intro demo with a VP of Sales (mid-market).",
    threadId: "thr_demo_001",
    repliedAt: D(-6),
  },
  {
    id: "e_demo_002",
    contactId: "c_demo_001",
    campaignId: "cmp_demo_001",
    sequenceEnrollmentId: "",
    stepIndex: "",
    variant: "B",
    subject: "EU expansion + outbound — quick thought",
    body:
      "Hi Maya,\n\nFollowing up on the EU expansion — happy to share what's working " +
      "for similar GTM teams. 15 minutes Thursday?\n\n— You",
    sentAt: D(-2),
    status: "sent",
    aiGenerated: "yes",
    prompt: "Re-engage Maya at Northwind on EU expansion angle.",
    threadId: "thr_demo_002",
    repliedAt: "",
  },
  {
    id: "e_demo_003",
    contactId: "c_demo_002",
    campaignId: "cmp_demo_001",
    sequenceEnrollmentId: "",
    stepIndex: "",
    variant: "A",
    subject: "Pipeline analytics for Brightleaf",
    body:
      "Hi Diego,\n\nBrightleaf's growth posts on funnel hygiene caught my eye. " +
      "Curious if you've shopped tooling for outbound conversion reporting?\n\n— You",
    sentAt: D(-3),
    status: "sent",
    aiGenerated: "yes",
    prompt: "Book demo with Diego — angle on funnel analytics.",
    threadId: "thr_demo_003",
    repliedAt: D(-1),
  },
  {
    id: "e_demo_004",
    contactId: "c_demo_003",
    campaignId: "cmp_demo_002",
    sequenceEnrollmentId: "en_demo_001",
    stepIndex: "0",
    variant: "",
    subject: "Outbound tooling for Tidewater",
    body:
      "Hi Priya,\n\nSeries A founder myself once — outbound tooling was always " +
      "the headache. Worth a 15-min compare?\n\n— You",
    sentAt: D(-1),
    status: "sent",
    aiGenerated: "yes",
    prompt: "Book design partner conversation with Series A founder.",
    threadId: "thr_demo_004",
    repliedAt: "",
  },
  {
    id: "e_demo_005",
    contactId: "c_demo_005",
    campaignId: "cmp_demo_001",
    sequenceEnrollmentId: "",
    stepIndex: "",
    variant: "",
    subject: "Helix Sales Ops — quick idea",
    body:
      "Hi Sara,\n\nNoticed Helix is hiring SDRs — usually a sign sales ops is " +
      "thinking about outbound tooling. 10 minutes next week?\n\n— You",
    sentAt: D(-1),
    status: "sent",
    aiGenerated: "yes",
    prompt: "Open conversation with Sales Ops Director at healthcare company.",
    threadId: "thr_demo_005",
    repliedAt: "",
  },
];

export const SEED_TASKS: Task[] = [
  {
    id: "t_demo_001",
    contactId: "c_demo_001",
    title: "Send pricing one-pager",
    dueAt: D(2).slice(0, 10),
    status: "open",
    owner: "you@yourco.example",
    notes: "Maya asked for it on the call.",
    createdAt: D(-2),
    completedAt: "",
  },
  {
    id: "t_demo_002",
    contactId: "c_demo_002",
    title: "Demo with Diego (Tuesday 11am PT)",
    dueAt: D(1).slice(0, 10),
    status: "open",
    owner: "you@yourco.example",
    notes: "",
    createdAt: D(-1),
    completedAt: "",
  },
  {
    id: "t_demo_003",
    contactId: "c_demo_005",
    title: "Loop in IT contact at Helix",
    dueAt: D(0).slice(0, 10),
    status: "open",
    owner: "you@yourco.example",
    notes: "Procurement gate is RevOps; we need an IT champion too.",
    createdAt: D(-1),
    completedAt: "",
  },
  {
    id: "t_demo_004",
    contactId: "c_demo_004",
    title: "Schedule kickoff with Apex",
    dueAt: D(-1).slice(0, 10),
    status: "done",
    owner: "you@yourco.example",
    notes: "",
    createdAt: D(-3),
    completedAt: D(-1),
  },
];

export const SEED_ACTIVITY: Activity[] = [
  {
    id: "a_demo_001",
    contactId: "c_demo_001",
    type: "email_sent",
    summary: "Sent: Quick idea for Northwind Logistics",
    meta: '{"variant":"A"}',
    createdAt: D(-7),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_002",
    contactId: "c_demo_001",
    type: "email_replied",
    summary: "Reply received: Quick idea for Northwind Logistics",
    meta: "",
    createdAt: D(-6),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_003",
    contactId: "c_demo_001",
    type: "stage_change",
    summary: "Stage: contacted → engaged (reply detected)",
    meta: "",
    createdAt: D(-6),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_004",
    contactId: "c_demo_001",
    type: "score_updated",
    summary: "AI score: 88 — Decision-maker title at ICP-fit company; replied to opener.",
    meta: '{"score":88}',
    createdAt: D(-2),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_005",
    contactId: "c_demo_002",
    type: "email_sent",
    summary: "Sent: Pipeline analytics for Brightleaf",
    meta: "",
    createdAt: D(-3),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_006",
    contactId: "c_demo_002",
    type: "email_replied",
    summary: "Reply received: Pipeline analytics for Brightleaf",
    meta: "",
    createdAt: D(-1),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_007",
    contactId: "c_demo_002",
    type: "stage_change",
    summary: "Stage: contacted → qualified",
    meta: "",
    createdAt: D(-1),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_008",
    contactId: "c_demo_003",
    type: "sequence_enrolled",
    summary: "Enrolled in sequence",
    meta: '{"sequenceId":"seq_demo_001"}',
    createdAt: D(-1),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_009",
    contactId: "c_demo_003",
    type: "email_sent",
    summary: "Sequence step 1: Outbound tooling for Tidewater",
    meta: "",
    createdAt: D(-1),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_010",
    contactId: "c_demo_008",
    type: "form_submission",
    summary: "Form: Contact us",
    meta: '{"slug":"contact-us"}',
    createdAt: D(-1),
    actor: "form",
  },
];

export const SEED_SEQUENCES: Sequence[] = [
  {
    id: "seq_demo_001",
    name: "Founder 3-touch",
    goal: "Land design-partner conversations with Series A founders.",
    tone: "warm, direct, peer-to-peer",
    status: "active",
    createdAt: D(-14),
  },
];

export const SEED_SEQUENCE_STEPS: SequenceStep[] = [
  {
    id: "step_demo_001",
    sequenceId: "seq_demo_001",
    stepIndex: "0",
    delayDays: "0",
    subjectHint: "Quick intro",
    instructions: "Open. Reference recent funding or hiring signal.",
    createdAt: D(-14),
  },
  {
    id: "step_demo_002",
    sequenceId: "seq_demo_001",
    stepIndex: "1",
    delayDays: "3",
    subjectHint: "Following up",
    instructions: "Different angle. Share a customer outcome.",
    createdAt: D(-14),
  },
  {
    id: "step_demo_003",
    sequenceId: "seq_demo_001",
    stepIndex: "2",
    delayDays: "5",
    subjectHint: "Last note for now",
    instructions: "Soft breakup. Leave the door open.",
    createdAt: D(-14),
  },
];

export const SEED_ENROLLMENTS: Enrollment[] = [
  {
    id: "en_demo_001",
    sequenceId: "seq_demo_001",
    contactId: "c_demo_003",
    status: "active",
    currentStep: "1",
    nextRunAt: D(2),
    lastRunAt: D(-1),
    createdAt: D(-1),
    stoppedReason: "",
  },
];

export const SEED_COMPANIES: Company[] = [
  {
    id: "co_demo_001",
    name: "Northwind Logistics",
    domain: "northwind.example",
    industry: "Logistics",
    size: "500-1000",
    website: "https://northwind.example",
    notes: "Mid-market; expanding to EU.",
    createdAt: D(-21),
    updatedAt: D(-2),
  },
];

export const SEED_FORMS: FormDef[] = [
  {
    id: "f_demo_001",
    slug: "contact-us",
    name: "Contact us",
    fields: '["name","email","company","role","notes"]',
    redirectUrl: "",
    tags: "form",
    sequenceId: "",
    createdAt: D(-9),
  },
  {
    id: "f_demo_002",
    slug: "demo-request",
    name: "Request a demo",
    fields: '["name","email","company","role"]',
    redirectUrl: "",
    tags: "demo-request",
    sequenceId: "seq_demo_001",
    createdAt: D(-7),
  },
];

export const SEED_VIEWS: SavedView[] = [
  {
    id: "v_demo_001",
    name: "Hot ICPs",
    filter: '{"tag":"ICP","minScore":80}',
    createdAt: D(-7),
  },
  {
    id: "v_demo_002",
    name: "Untouched leads",
    filter: '{"stage":"new"}',
    createdAt: D(-7),
  },
];
